### ISSUE TITLE
Maybe compile using the Pixel Experience Source?

### ISSUE THREAD

**Issue by uavana** [ShihabZzz/Releases#2]
Pixel Experience is also based on lineage os, and it's much more prettier and easy to use compare to lineage os.
Icons of lineage os are really ugly.

**Comment by ShihabZzz** [comment]
PixelExperience isn't LineageOS based. Though i never find out to easy to use that ROM ( Pixel ). 

About compiling- Give me server to build , maybe i can build it.

BTW don't write these things here. This is for only bug report.
